import EditSections from "@/components/EditSections";
import NewSection from "@/components/NewSection";
import {
  EditMode,
  SectionEdit,
  Questions,
  SectionVal,
  CTX,
  Quiz,
} from "@/components/types";
import Head from "next/head";
import React, { useEffect, useState } from "react";

function QuizSetup() {
  const [quizState, updateQuiz] = useState<Quiz>({
    owner: {
      ownerName: "",
      quizName: "",
      id: 0,
    },
    Sections: {},
    Questions: {},
  });

  useEffect(() => {
    console.log(quizState);
  }, [quizState]);
  const [editMode, updateMode] = useState<EditMode>("OWNER");
  const [sectionEdit, selectSection] = useState<SectionEdit>(null);

  const [questions, updateQuestions] = useState<Questions>({});

  const createQuiz = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const ownerName = e.currentTarget.owner.value;
    const quizName = e.currentTarget.quizName.value;
    console.log(ownerName, quizName);
    const quiz: Quiz = {
      owner: {
        ownerName,
        quizName,
        id: 0,
      },
      Sections: {},
      Questions: {},
    };
  };

  const editSectionBtn = (sectionKey: string) => {
    updateMode("QUESTIONS");
    selectSection(`${sectionKey}`);
  };

  const goBack = () => {
    if (editMode === "QUESTIONS") {
      updateMode("SECTIONS");
    } else {
      updateMode("QUESTIONS");
    }
  };

  const renderSwitch = () => {
    switch (editMode) {
      case "OWNER":
        return (
          <div className="md:w-3/12 w-7/12 mx-auto my-5">
            <form onSubmit={(e) => createQuiz(e)}>
              <label htmlFor="owner">Quiz Creator</label>
              <input
                type="text"
                id="owner"
                required
                minLength={3}
                className="bg-red-300 valid:bg-white valid:text-black w-full"
              ></input>
              <label htmlFor="quizName">Quiz Name</label>
              <input
                type="text"
                id="quizName"
                required
                minLength={3}
                className="bg-red-300 valid:bg-white valid:text-black w-full"
              ></input>
              <button type="submit">Submit</button>
            </form>
          </div>
        );
      case "SECTIONS":
        return (
          <div>
            <NewSection />
            {Object.values(quizState.Sections).length > 0 &&
              Object.keys(quizState.Sections).map((sec: string, n: number) => {
                return (
                  <div
                    className="md:w-3/12 w-7/12 mx-auto my-5 aspect-video flex justify-center items-center first:rounded-t-lg last:rounded-b-lg"
                    style={{
                      background: `url(${quizState.Sections[sec].background})`,
                      backgroundSize: "cover",
                      backgroundPosition: "center",
                    }}
                    key={`section${n}`}
                  >
                    <h1
                      onClick={() => editSectionBtn(sec)}
                      className="text-center text-xl border-2 px-5 py-2 backdrop-blur-sm cursor-pointer hover:px-6 hover:py-3 hover:text-2xl ease-in-out duration-500 bg-opacity-30 bg-zinc-700"
                    >
                      Update section
                      <br />
                      <span
                        className=" border-b-0 hover:border-b
              "
                      >
                        {quizState.Sections[sec].name}
                      </span>
                    </h1>
                  </div>
                );
              })}
          </div>
        );
      case "QUESTIONS":
        if (sectionEdit !== null) {
          return (
            <EditSections
              sectionKey={sectionEdit}
              sectionTitle={quizState.Sections[sectionEdit].name}
              sectionImgUrl={quizState.Sections[sectionEdit].name}
              questions={questions}
              updateMode={goBack}
            />
          );
        }

      default:
        break;
    }
  };

  return (
    <CTX.Provider value={[quizState, updateQuiz]}>
      <div>
        <Head>
          <title>Quiz Set Up</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {renderSwitch()}
      </div>
    </CTX.Provider>
  );
}

export default QuizSetup;
