import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";

import io from "socket.io-client";
import Link from "next/link";
import Util from "@/components/util";
import { ServerSideProps } from "@/components/types";

export default function Home(props: ServerSideProps) {
  const [socket, setConnection] = useState<WebSocket>();

  useEffect(() => {
    console.log(props);
    const socket = new WebSocket("ws://localhost:4001/ws");
    socket.onopen = () => {
      console.log("connected");
      socket.send("hello");
    };
    setConnection(socket);
    // socket.onmessage = (e) => {
    //   console.log(e.data);
    // };
    // socket.onclose = () => {
    //   console.log("disconnected");
    // };

    // socket.on("connect", () => {});
    // socket.on("msg", (props) => {
    //   console.log(props);
    // });
  }, []);

  const btnClick = () => {
    // socket.emit("submit", `${socket.id} button pressed`);
    socket?.send(`{hello: "world"}`);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <button
            className=" border-4 border-red-300"
            onClick={() => btnClick()}
          >
            Click Me
          </button>
          <Link href={"/setup"}>set up</Link>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  return {
    props: {
      base: Util.baseURL(),
    },
  };
}
