import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";

import io from "socket.io-client";

const inter = Inter({ subsets: ["latin"] });
const socket = io("http://localhost:8080", {
  transports: ["websocket", "polling"],
});

export default function Home() {
  useEffect(() => {
    socket.on("connect", () => {});
    socket.on("msg", (props) => {
      console.log(props);
    });
  }, []);

  const btnClick = () => {
    socket.emit("submit", `${socket.id} button pressed`);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <button
            className=" border-4 border-red-300 text-6xl"
            onClick={() => btnClick()}
          >
            Click Me
          </button>
        </div>
      </main>
    </>
  );
}
